<?php
if(is_category(8))
    get_template_part('category','gallery');
elseif(is_category(7))
    get_template_part('category','news');
elseif(is_category(9))
    get_template_part('category','q-r');
else
    get_template_part('category','product');
